### ISSUE TITLE
RTC vs Git

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/teaser-training-uk-20170518#1]
# TODOs
- [x] creating a new branch
- [x] duplicating a branch
- [x] merging two branches
- [x] check in and check out
- [x] compare 
- [x] tracing changes 
- [x] managing change sets
- [x] eclipse client and vs client

@stoe please look at this.
